# DO NOT EDIT this file! Use settings.py instead.
# This file contains default values of ContWatch configuration settings.

LOG_FILE = "contwatch.log"
LOG_FILE_MAX_BYTES = 51200
LOG_FILE_BACKUP_COUNT = 5
LOG_LEVEL = "DEBUG"

DB_TYPE = "sqlite"
DB_SQLITE_FILE = "database.sqlite"
DB_HOST = ""
DB_USER = ""
DB_PASSWORD = ""
DB_DATABASE = "contwatch"
DB_DATA_READONLY = False

WEB_SERVER = True
WEB_SERVER_ADDRESS = "0.0.0.0"
WEB_SERVER_PORT = 80
WEB_SERVER_DEBUG = False
WEB_SERVER_ORIGINS = "*"

CACHING_INTERVAL = 10
CACHING_ASYNC = False
