# ContWatch configuration settings default values
# DO NOT EDIT this file, use settings.py instead.

LOG_FILE = "contwatch.log"
LOG_FILE_MAX_BYTES = 51200
LOG_FILE_BACKUP_COUNT = 5
LOG_LEVEL = "DEBUG"

DATABASE_FILE = "database.sqlite"

WEB_SERVER_ADDRESS = "0.0.0.0"
WEB_SERVER_PORT = 80
WEB_SERVER_DEBUG = False

CACHING_INTERVAL = 10
CACHING_ASYNC = False
