"""add_handler_order_column

Revision ID: 49ffc72226c1
Revises: 64cdc243d449
Create Date: 2026-03-02 19:39:03.701424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ffc72226c1'
down_revision: Union[str, Sequence[str], None] = '64cdc243d449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handlers', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handlers', 'order')
    # ### end Alembic commands ###
