"""drop_unused_units_table

Revision ID: 60795099e1bf
Revises: f4dd33462c82
Create Date: 2026-03-06 07:58:08.724489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60795099e1bf'
down_revision: Union[str, Sequence[str], None] = 'f4dd33462c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_base_unit'), table_name='units')
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('base_unit', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('base_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units'))
    )
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    op.create_index(op.f('ix_units_base_unit'), 'units', ['base_unit'], unique=False)
    # ### end Alembic commands ###
