"""add widget_sliders table

Revision ID: 64cdc243d449
Revises: a1b2c3d4e5f6
Create Date: 2026-03-02 14:23:14.244320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cdc243d449'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_sliders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('param_key', sa.String(length=100), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('step', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_widget_sliders_action_id_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widget_sliders_attribute_id_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_sliders'))
    )
    op.create_index(op.f('ix_widget_sliders_name'), 'widget_sliders', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_sliders_name'), table_name='widget_sliders')
    op.drop_table('widget_sliders')
    # ### end Alembic commands ###
