"""add sub_workflows table

Revision ID: 96db4b158ec4
Revises: a8908de4ea3e
Create Date: 2026-03-08 15:01:40.215422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96db4b158ec4'
down_revision: Union[str, Sequence[str], None] = 'a8908de4ea3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('graph', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_workflows'))
    )
    op.create_index(op.f('ix_sub_workflows_name'), 'sub_workflows', ['name'], unique=False)
    op.create_index(op.f('ix_sub_workflows_user_id'), 'sub_workflows', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_workflows_user_id'), table_name='sub_workflows')
    op.drop_index(op.f('ix_sub_workflows_name'), table_name='sub_workflows')
    op.drop_table('sub_workflows')
    # ### end Alembic commands ###
