"""initial schema

Revision ID: b0eed7d52744
Revises: 
Create Date: 2026-02-28 08:17:31.968125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0eed7d52744'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    op.create_index(op.f('ix_actions_name'), 'actions', ['name'], unique=False)
    op.create_table('handlers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handlers'))
    )
    op.create_table('logging_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logging_messages'))
    )
    op.create_index(op.f('ix_logging_messages_date'), 'logging_messages', ['date'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('actions_node_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_unit', sa.String(length=100), nullable=True),
    sa.Column('base_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units'))
    )
    op.create_index(op.f('ix_units_base_unit'), 'units', ['base_unit'], unique=False)
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('rounding', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], name=op.f('fk_attributes_handler_id_handlers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attributes'))
    )
    op.create_index(op.f('ix_attributes_name'), 'attributes', ['name'], unique=False)
    op.create_table('data_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_data_stats_attribute_id_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_stats'))
    )
    op.create_index(op.f('ix_data_stats_attribute_id'), 'data_stats', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_data_stats_date'), 'data_stats', ['date'], unique=False)
    op.create_table('data_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_data_units_attribute_id_attributes')),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], name=op.f('fk_data_units_handler_id_handlers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_units'))
    )
    op.create_index('ix_data_units_attribute_date', 'data_units', ['attribute_id', 'date'], unique=False)
    op.create_index(op.f('ix_data_units_attribute_id'), 'data_units', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_data_units_date'), 'data_units', ['date'], unique=False)
    op.create_table('widget_switches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('attribute_compare', sa.String(length=100), nullable=True),
    sa.Column('action_on_id', sa.Integer(), nullable=True),
    sa.Column('action_off_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_off_id'], ['actions.id'], name=op.f('fk_widget_switches_action_off_id_actions')),
    sa.ForeignKeyConstraint(['action_on_id'], ['actions.id'], name=op.f('fk_widget_switches_action_on_id_actions')),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widget_switches_attribute_id_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_switches'))
    )
    op.create_index(op.f('ix_widget_switches_name'), 'widget_switches', ['name'], unique=False)
    op.create_table('widget_tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widget_tiles_attribute_id_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_tiles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_tiles')
    op.drop_index(op.f('ix_widget_switches_name'), table_name='widget_switches')
    op.drop_table('widget_switches')
    op.drop_index(op.f('ix_data_units_date'), table_name='data_units')
    op.drop_index(op.f('ix_data_units_attribute_id'), table_name='data_units')
    op.drop_index('ix_data_units_attribute_date', table_name='data_units')
    op.drop_table('data_units')
    op.drop_index(op.f('ix_data_stats_date'), table_name='data_stats')
    op.drop_index(op.f('ix_data_stats_attribute_id'), table_name='data_stats')
    op.drop_table('data_stats')
    op.drop_index(op.f('ix_attributes_name'), table_name='attributes')
    op.drop_table('attributes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_index(op.f('ix_units_base_unit'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_logging_messages_date'), table_name='logging_messages')
    op.drop_table('logging_messages')
    op.drop_table('handlers')
    op.drop_index(op.f('ix_actions_name'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
