"""initial schema

Revision ID: c231be9a42aa
Revises: 
Create Date: 2026-03-03 10:16:40.410478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text as sa_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c231be9a42aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handlers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handlers'))
    )
    op.create_table('logging_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logging_messages'))
    )
    op.create_index(op.f('ix_logging_messages_timestamp'), 'logging_messages', ['timestamp'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('actions_node_map', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_unit', sa.String(length=100), nullable=True),
    sa.Column('base_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units'))
    )
    op.create_index(op.f('ix_units_base_unit'), 'units', ['base_unit'], unique=False)
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], name=op.f('fk_actions_handler_id_handlers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    op.create_index(op.f('ix_actions_name'), 'actions', ['name'], unique=False)
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('rounding', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], name=op.f('fk_attributes_handler_id_handlers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attributes'))
    )
    op.create_index(op.f('ix_attributes_name'), 'attributes', ['name'], unique=False)
    op.create_table('data_units',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_data_units_attribute_id_attributes')),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.id'], name=op.f('fk_data_units_handler_id_handlers')),
    sa.PrimaryKeyConstraint('timestamp', 'attribute_id', name=op.f('pk_data_units'))
    )

    # --- TimescaleDB setup ---
    conn = op.get_bind()
    conn.execute(sa_text("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE"))
    conn.execute(
        sa_text("SELECT create_hypertable('data_units', 'timestamp', migrate_data => true)")
    )
    conn.execute(
        sa_text(
            "CREATE INDEX ix_data_units_attribute_id "
            "ON data_units (attribute_id, timestamp DESC)"
        )
    )
    conn.execute(
        sa_text("""
            CREATE MATERIALIZED VIEW daily_stats
            WITH (timescaledb.continuous) AS
            SELECT
                time_bucket('1 day', timestamp) AS bucket,
                attribute_id,
                MIN(value) AS min_value,
                MAX(value) AS max_value
            FROM data_units
            GROUP BY bucket, attribute_id
            WITH NO DATA
        """)
    )
    conn.execute(
        sa_text("""
            SELECT add_continuous_aggregate_policy('daily_stats',
                start_offset => INTERVAL '3 days',
                end_offset   => INTERVAL '1 hour',
                schedule_interval => INTERVAL '1 hour'
            )
        """)
    )

    op.create_table('widget_sliders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('param_key', sa.String(length=100), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('step', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_widget_sliders_action_id_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widget_sliders_attribute_id_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_sliders'))
    )
    op.create_index(op.f('ix_widget_sliders_name'), 'widget_sliders', ['name'], unique=False)
    op.create_table('widget_switches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('attribute_compare', sa.String(length=100), nullable=True),
    sa.Column('action_on_id', sa.Integer(), nullable=True),
    sa.Column('action_off_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_off_id'], ['actions.id'], name=op.f('fk_widget_switches_action_off_id_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['action_on_id'], ['actions.id'], name=op.f('fk_widget_switches_action_on_id_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widget_switches_attribute_id_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_switches'))
    )
    op.create_index(op.f('ix_widget_switches_name'), 'widget_switches', ['name'], unique=False)
    op.create_table('widget_tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widget_tiles_attribute_id_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_tiles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_tiles')
    op.drop_index(op.f('ix_widget_switches_name'), table_name='widget_switches')
    op.drop_table('widget_switches')
    op.drop_index(op.f('ix_widget_sliders_name'), table_name='widget_sliders')
    op.drop_table('widget_sliders')
    # --- TimescaleDB teardown ---
    conn = op.get_bind()
    conn.execute(sa_text("SELECT remove_continuous_aggregate_policy('daily_stats', if_exists => true)"))
    conn.execute(sa_text("DROP MATERIALIZED VIEW IF EXISTS daily_stats"))

    op.drop_table('data_units')
    op.drop_index(op.f('ix_attributes_name'), table_name='attributes')
    op.drop_table('attributes')
    op.drop_index(op.f('ix_actions_name'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_index(op.f('ix_units_base_unit'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_logging_messages_timestamp'), table_name='logging_messages')
    op.drop_table('logging_messages')
    op.drop_table('handlers')
    # ### end Alembic commands ###
