"""add ondelete cascade to widget attribute_id fks

Revision ID: c86cf49ccc34
Revises: 60795099e1bf
Create Date: 2026-03-06 08:12:05.447125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86cf49ccc34'
down_revision: Union[str, Sequence[str], None] = '60795099e1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_widget_sliders_attribute_id_attributes'), 'widget_sliders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_widget_sliders_attribute_id_attributes'), 'widget_sliders', 'attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_widget_switches_attribute_id_attributes'), 'widget_switches', type_='foreignkey')
    op.create_foreign_key(op.f('fk_widget_switches_attribute_id_attributes'), 'widget_switches', 'attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_widget_tiles_attribute_id_attributes'), 'widget_tiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_widget_tiles_attribute_id_attributes'), 'widget_tiles', 'attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_widget_tiles_attribute_id_attributes'), 'widget_tiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_widget_tiles_attribute_id_attributes'), 'widget_tiles', 'attributes', ['attribute_id'], ['id'])
    op.drop_constraint(op.f('fk_widget_switches_attribute_id_attributes'), 'widget_switches', type_='foreignkey')
    op.create_foreign_key(op.f('fk_widget_switches_attribute_id_attributes'), 'widget_switches', 'attributes', ['attribute_id'], ['id'])
    op.drop_constraint(op.f('fk_widget_sliders_attribute_id_attributes'), 'widget_sliders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_widget_sliders_attribute_id_attributes'), 'widget_sliders', 'attributes', ['attribute_id'], ['id'])
    # ### end Alembic commands ###
