"""unified widgets table

Revision ID: d5f0c1ae7a1d
Revises: c86cf49ccc34
Create Date: 2026-03-06 08:55:34.925906

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5f0c1ae7a1d'
down_revision: Union[str, Sequence[str], None] = 'c86cf49ccc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widgets_attribute_id_attributes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widgets'))
    )

    # --- Data migration: copy from old tables into unified widgets ---
    conn = op.get_bind()

    # Tiles (order: 1, 2, 3, ...)
    tiles = conn.execute(sa.text("SELECT id, attribute_id FROM widget_tiles ORDER BY id")).fetchall()
    order = 0
    for row in tiles:
        order += 1
        conn.execute(sa.text(
            "INSERT INTO widgets (type, \"order\", attribute_id, config) "
            "VALUES ('tile', :order, :attr_id, '{}')"
        ), {"order": order, "attr_id": row[1]})

    # Switches
    switches = conn.execute(sa.text(
        "SELECT id, name, icon, attribute_id, attribute_compare, action_on_id, action_off_id "
        "FROM widget_switches ORDER BY id"
    )).fetchall()
    for row in switches:
        order += 1
        config = {}
        if row[4]:  # attribute_compare
            config["attribute_compare"] = row[4]
        if row[5]:  # action_on_id
            config["action_on_id"] = row[5]
        if row[6]:  # action_off_id
            config["action_off_id"] = row[6]
        conn.execute(sa.text(
            "INSERT INTO widgets (type, \"order\", name, icon, attribute_id, config) "
            "VALUES ('switch', :order, :name, :icon, :attr_id, :config)"
        ), {"order": order, "name": row[1], "icon": row[2], "attr_id": row[3], "config": json.dumps(config)})

    # Sliders
    sliders = conn.execute(sa.text(
        "SELECT id, name, icon, attribute_id, action_id, param_key, min, max, step, unit "
        "FROM widget_sliders ORDER BY id"
    )).fetchall()
    for row in sliders:
        order += 1
        config = {
            "action_id": row[4],
            "param_key": row[5],
            "min": row[6],
            "max": row[7],
            "step": row[8],
        }
        conn.execute(sa.text(
            "INSERT INTO widgets (type, \"order\", name, icon, attribute_id, config) "
            "VALUES ('slider', :order, :name, :icon, :attr_id, :config)"
        ), {"order": order, "name": row[1], "icon": row[2], "attr_id": row[3], "config": json.dumps(config)})

    # --- Drop old tables ---
    op.drop_index(op.f('ix_widget_switches_name'), table_name='widget_switches')
    op.drop_table('widget_switches')
    op.drop_table('widget_tiles')
    op.drop_index(op.f('ix_widget_sliders_name'), table_name='widget_sliders')
    op.drop_table('widget_sliders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_sliders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('param_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('step', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_widget_sliders_action_id_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widget_sliders_attribute_id_attributes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_sliders'))
    )
    op.create_index(op.f('ix_widget_sliders_name'), 'widget_sliders', ['name'], unique=False)
    op.create_table('widget_tiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widget_tiles_attribute_id_attributes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_tiles'))
    )
    op.create_table('widget_switches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_compare', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action_on_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_off_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_off_id'], ['actions.id'], name=op.f('fk_widget_switches_action_off_id_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['action_on_id'], ['actions.id'], name=op.f('fk_widget_switches_action_on_id_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_widget_switches_attribute_id_attributes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_switches'))
    )
    op.create_index(op.f('ix_widget_switches_name'), 'widget_switches', ['name'], unique=False)
    op.drop_table('widgets')
    # ### end Alembic commands ###
