"""add indexes on attribute handler_id enabled and action handler_id

Revision ID: e21044117ef6
Revises: 96db4b158ec4
Create Date: 2026-03-09 09:13:01.929799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21044117ef6'
down_revision: Union[str, Sequence[str], None] = '96db4b158ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_actions_handler_id'), 'actions', ['handler_id'], unique=False)
    op.create_index(op.f('ix_attributes_enabled'), 'attributes', ['enabled'], unique=False)
    op.create_index(op.f('ix_attributes_handler_id'), 'attributes', ['handler_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attributes_handler_id'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_enabled'), table_name='attributes')
    op.drop_index(op.f('ix_actions_handler_id'), table_name='actions')
    # ### end Alembic commands ###
