"""add on_delete_cascade to data_unit foreign keys

Revision ID: f4dd33462c82
Revises: a39b0091f574
Create Date: 2026-03-04 15:51:44.924011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4dd33462c82'
down_revision: Union[str, Sequence[str], None] = 'a39b0091f574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_data_units_handler_id_handlers'), 'data_units', type_='foreignkey')
    op.drop_constraint(op.f('fk_data_units_attribute_id_attributes'), 'data_units', type_='foreignkey')
    op.create_foreign_key(op.f('fk_data_units_handler_id_handlers'), 'data_units', 'handlers', ['handler_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_data_units_attribute_id_attributes'), 'data_units', 'attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_data_units_attribute_id_attributes'), 'data_units', type_='foreignkey')
    op.drop_constraint(op.f('fk_data_units_handler_id_handlers'), 'data_units', type_='foreignkey')
    op.create_foreign_key(op.f('fk_data_units_attribute_id_attributes'), 'data_units', 'attributes', ['attribute_id'], ['id'])
    op.create_foreign_key(op.f('fk_data_units_handler_id_handlers'), 'data_units', 'handlers', ['handler_id'], ['id'])
    # ### end Alembic commands ###
