"""add handler confirm_actions

Revision ID: f7325da33dd8
Revises: c231be9a42aa
Create Date: 2026-03-04 08:15:51.273550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7325da33dd8'
down_revision: Union[str, Sequence[str], None] = 'c231be9a42aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handlers', sa.Column('confirm_actions', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handlers', 'confirm_actions')
    # ### end Alembic commands ###
