/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedInspectorRouteImport } from './routes/_authenticated/inspector'
import { Route as AuthenticatedHandlersRouteImport } from './routes/_authenticated/handlers'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActionsRouteImport } from './routes/_authenticated/actions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInspectorRoute = AuthenticatedInspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHandlersRoute = AuthenticatedHandlersRouteImport.update({
  id: '/handlers',
  path: '/handlers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActionsRoute = AuthenticatedActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/handlers': typeof AuthenticatedHandlersRoute
  '/inspector': typeof AuthenticatedInspectorRoute
  '/logs': typeof AuthenticatedLogsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/handlers': typeof AuthenticatedHandlersRoute
  '/inspector': typeof AuthenticatedInspectorRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/actions': typeof AuthenticatedActionsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/handlers': typeof AuthenticatedHandlersRoute
  '/_authenticated/inspector': typeof AuthenticatedInspectorRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/actions'
    | '/admin'
    | '/handlers'
    | '/inspector'
    | '/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/actions'
    | '/admin'
    | '/handlers'
    | '/inspector'
    | '/logs'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/actions'
    | '/_authenticated/admin'
    | '/_authenticated/handlers'
    | '/_authenticated/inspector'
    | '/_authenticated/logs'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspector': {
      id: '/_authenticated/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof AuthenticatedInspectorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/handlers': {
      id: '/_authenticated/handlers'
      path: '/handlers'
      fullPath: '/handlers'
      preLoaderRoute: typeof AuthenticatedHandlersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActionsRoute: typeof AuthenticatedActionsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHandlersRoute: typeof AuthenticatedHandlersRoute
  AuthenticatedInspectorRoute: typeof AuthenticatedInspectorRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActionsRoute: AuthenticatedActionsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHandlersRoute: AuthenticatedHandlersRoute,
  AuthenticatedInspectorRoute: AuthenticatedInspectorRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
