services:
  client:
    environment:
      TURBO_TEAM: "$TURBO_TEAM"
      TURBO_TOKEN: "$TURBO_TOKEN"
    build:
      context: client
      dockerfile: ./apps/contwatch-client/Dockerfile
    restart: always
    network_mode: host
  api:
    build:
      context: server
    restart: always
    working_dir: /api
    network_mode: host
    privileged: true
