name: Frontend CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v3
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Client build
        run: bun run build
      - name: Stylelint
        run: bun run stylelint
      - name: Test
        run: bun test
