name: Frontend CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    defaults:
      run:
        working-directory: ./src/client

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Client build
        run: npm run build
      - name: Stylelint
        run: npm run stylelint
      - name: Test
        run: npm run test
