name: Client CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    defaults:
      run:
        working-directory: ./src/client

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Biome
        run: npm run biome
      - name: Stylelint
        run: npm run stylelint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
